### ISSUE TITLE
attest build provenance

### ISSUE THREAD

**Issue by jakoch** [jakoch/cpp-devbox#15]
- https://github.com/actions/attest-build-provenance?tab=readme-ov-file#container-image

```
- name: Attest
  uses: actions/attest-build-provenance@v2
  id: attest
  with:
    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    subject-digest: ${{ steps.push.outputs.digest }}
    push-to-registry: true
```
