### ISSUE TITLE
add docker/scout-action

### ISSUE THREAD

**Issue by jakoch** [jakoch/cpp-devbox#18]
- [ ] add docker/scout-action
  - the local image is build and loaded and compared against the one pushed to the registry?
- [ ] upload sarif?

```
- name: Docker Scout
  id: docker-scout
  uses: docker/scout-action@v1
  with:
    command: cves,recommendations,compare
    to-latest: false
    to: ${{ IMAGES }}:${{ COMPARE_TAG }}
    image: ${{ IMAGES }}:${{ IMAGE_TAG }}
    ignore-base: true
    ignore-unchanged: true
    only-fixed: ${{ ONLY-FIXED }}
    write-comment: ${{ WRITE-COMMENT }}
    github-token: ${{ secrets.TOKEN }}
```
